# Generated by Django 4.2 on 2023-08-06 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=168)),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField()),
                ('preparation_time_unit', models.CharField(max_length=16)),
                ('servings', models.IntegerField()),
                ('servings_unit', models.CharField(max_length=16)),
                ('preparation_steps', models.TextField()),
                ('preparation_steps_is_html', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_publushed', models.BooleanField(default=False)),
                ('cover', models.ImageField(
                    upload_to='recipes/covers/%Y/%m/%d/'
                )),
                ('author', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL
                )),
                ('category', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    to='recipes.category'
                )),
            ],
        ),
    ]
